### ISSUE TITLE
Data specification for Lagrangian filtering in a small region

### ISSUE THREAD

**Issue by cspencerjones** [rabernat/pleiades_llc_recipes#8]
For Lagrangian filtering, the following fields are absolutely necessary:
- UVEL
- VVEL
- Eta
- Phibot

Theta and Salt are highly desirable. I only UVEL, VVEL, Theta and Salt at the surface. Times should be from 390528 (Jan 1st at midnight) onwards for 1752 hours. face=1, i=slice(1080,3240), j=slice(0,2160). 

Initial code for doing this slicing is in #7 . I am going to keep working on this, but once @rsaim has access he can hopefully help.

**Comment by cspencerjones** [comment]
@rsaim I would love it if you could try to create the nc files for Theta and Salt (k=0 only) and put them in `/nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/sub-output`. The first step in trying to do this is to run a singularity container in your own scratch directory as explained here: https://hackmd.io/@eHN2gDGTS7uR1j3KZ26AJQ/HkTSyVMZi

After that, a lot of the code you will need is in #7 . `job_extract.sh` is the file that tells the supercomputer to run a singularity container and from there `extract.sh` is called, which loops in time. Please modify these and get them working to produce a few files in your own directory (that will mean modifying a lot of the paths and commenting/uncommenting the relevant lines in `extract.sh`), before you try adding files inside my file tree. You can comment here if you are having trouble, or hit me up on Slack. 

(note for others: I have given @rsaim the permissions to write files in `/nobackup/csjone15/pleiades_llc_recipes/python_cli_data_export/sub-output` already)

**Comment by rsaim** [comment]
Thank you for stating the requirements @cspencerjones! I'll start working on it.

**Comment by cspencerjones** [comment]
How are you doing with this @rsaim ? Can I do anything to make this easier?

**Comment by rsaim** [comment]
I did some [refactoring](https://github.com/ocean-transport/pleiades_llc_recipes/commit/7c8c462e5fa820f1141e7e8fad5c2eaaeed8c56d) yesterday. I'll follow up with you on Slack in a bit. Sorry for the delay.

**Comment by rsaim** [comment]
This is done as per confirmation by @cspencerjones on Slack.
